# Tensors
Source: https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html
        
Tensors are a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other hardware accelerators. In fact, tensors and NumPy arrays can often share the same underlying memory, eliminating the need to copy data (see Bridge with NumPy). Tensors are also optimized for automatic differentiation (we’ll see more about that later in the Autograd section). If you’re familiar with ndarrays, you’ll be right at home with the Tensor API. If not, follow along!        

In [1]:
import torch
import numpy as np

# Initializing a Tensor
Tensors can be initialized in various ways. Take a look at the following examples:

## Directly from data

Tensors can be created directly from data. The data type is automatically inferred.

In [2]:
data = [[1,2],[3,4]]

x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

## From a NumPy array

Tensors can be created from NumPy arrays (and vice versa - see Bridge with NumPy).


In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

## From another tensor:

The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

In [6]:
x_ones = torch.ones_like(x_data) # retains dtype and shape of data
print(x_ones)
x_random = torch.rand_like(x_data, dtype=torch.float)
print(x_random)

tensor([[1, 1],
        [1, 1]])
tensor([[0.3624, 0.7064],
        [0.3983, 0.8805]])


## With random or constant values:

shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [7]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor, ones_tensor, zeros_tensor)

tensor([[0.6600, 0.9194, 0.6351],
        [0.2405, 0.5237, 0.5453]]) tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor, ones_tensor, zeros_tensor)

tensor([[0.4543, 0.0115, 0.7712],
        [0.2184, 0.4443, 0.6150]]) tensor([[1., 1., 1.],
        [1., 1., 1.]]) tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Attributes of a Tensor

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [9]:
tensor = torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


# Operations on Tensors

Over 100 tensor operations, including arithmetic, linear algebra, matrix manipulation (transposing, indexing, slicing), sampling and more are comprehensively described https://pytorch.org/docs/stable/torch.html.

Each of these operations can be run on the GPU (at typically higher speeds than on a CPU). If you’re using Colab, allocate a GPU by going to Runtime > Change runtime type > GPU.

By default, tensors are created on the CPU. We need to explicitly move tensors to the GPU using .to method (after checking for GPU availability). Keep in mind that copying large tensors across devices can be expensive in terms of time and memory!

In [12]:
if torch.cuda.is_available():
    print('copy tensor to cuda')
    tensor = tensor.to('cuda')

copy tensor to cuda


Try out some of the operations from the list. If you’re familiar with the NumPy API, you’ll find the Tensor API a breeze to use.

## Standard numpy-like indexing and slicing:

In [13]:
tensor = torch.ones(4,4)
print('first row', tensor[0])
print('first column', tensor[:,0])
print('last column', tensor[:,-1])
tensor[:,1]=0
print(tensor)

first row tensor([1., 1., 1., 1.])
first column tensor([1., 1., 1., 1.])
last column tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## Joining tensors 
You can use torch.cat to concatenate a sequence of tensors along a given dimension. See also torch.stack, another tensor joining op that is subtly different from torch.cat.

In [14]:
t1 = torch.cat([tensor,tensor,tensor], dim=1)
t2 = torch.cat([tensor,tensor,tensor], dim=0)
print(t1)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## Arithmetic operations

### Matrix multiplication
This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value

In [20]:
tensor = torch.ones(4,4)
y1 = tensor @ tensor.T
print(y1)
y2 = tensor.matmul(tensor.T)
print(y2)
y3 = torch.rand_like(tensor)
print(y3)
torch.matmul(tensor, tensor.T,  out=y3)
print(y3)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[0.4182, 0.8375, 0.0550, 0.4596],
        [0.7335, 0.4747, 0.7435, 0.1521],
        [0.5325, 0.7443, 0.7649, 0.2439],
        [0.2249, 0.3616, 0.4802, 0.5375]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


### Element wise matrix multiplication

In [21]:
z1 = tensor * tensor
print(z1)
z2 = tensor.mul(tensor)
print(z2)
z3 = torch.rand_like(tensor)
print(z3)
torch.mul(tensor, tensor, out=z3)
print(z3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.8357, 0.7238, 0.2528, 0.6003],
        [0.2253, 0.9102, 0.9094, 0.6531],
        [0.7400, 0.0254, 0.2238, 0.4252],
        [0.3793, 0.2298, 0.0225, 0.1878]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


## Single-element tensors 
If you have a one-element tensor, for example by aggregating all values of a tensor into one value, you can convert it to a Python numerical value using item():

In [22]:
agg = tensor.sum()
agg_item = agg.item()
print(agg, type(agg))
print(agg_item, type(agg_item))

tensor(16.) <class 'torch.Tensor'>
16.0 <class 'float'>


## In-place operations 

Operations that store the result into the operand are called in-place. They are denoted by a _ suffix. For example: x.copy_(y), x.t_(), will change x.
- In-place operations save some memory, but can be problematic when computing derivatives because of an immediate loss of history. Hence, their use is discouraged.

In [25]:
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])
tensor([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]])


# Bridge with NumPy
Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.
## Tensor to NumPy array

In [29]:
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


A change in the tensor reflects in the NumPy array.

In [30]:
t.add_(1)
print(f't: {t}')
print(f'n: {n}')

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


## NumPy array to Tensor

In [34]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.

In [35]:
t.add_(3)
print(f't: {t}')
print(f'n: {n}')

t: tensor([4., 4., 4., 4., 4.], dtype=torch.float64)
n: [4. 4. 4. 4. 4.]
